Enable auth monitorConnectionServer
networkservicemesh/cmd-forwarder-sriov pull request #507
Opened 2022-07-29 15:30 UTC by anastasia-malysheva

Signed-off-by: anastasia.malysheva <anastasia.malysheva@xored.com>

2022-07-29 15:58 UTC, denis-tingaikin requested changes

2022-07-29 15:58 UTC, denis-tingaikin commented on main.go
> +		authmonitor.NewMonitorConnectionServer(),
Should we share the map?

2022-07-30 00:19 UTC, anastasia-malysheva commented on main.go
> +		authmonitor.NewMonitorConnectionServer(),
@denis-tingaikin fixed

2022-08-01 17:36 UTC, denis-tingaikin approved these changes

2022-08-01 17:36 UTC, merged